---

- name: Turn on analytics agent monitoring
  win_lineinfile:
    dest: "{{ machine_agent_dest_folder_win }}/monitors/analytics-agent/monitor.xml"
    regexp: '<enabled>false</enabled>'
    line: '<enabled>true</enabled>'
    backrefs: yes

- name: Configure the analytics agent properties file
  win_lineinfile:
    dest: "{{ machine_agent_dest_folder_win }}/monitors/analytics-agent/conf/analytics-agent.properties"
    regexp: "^{{ item.setting }}"
    line: "{{ item.setting }}{{ item.value }}"
  with_items:
    - { setting: 'ad.agent.name=', value: '{{ tier_name }}-ag' }
    - { setting: 'http.event.endpoint=', value: '{{ analytics_event_endpoint }}' }
    - { setting: 'ad.controller.url=', value: 'https://{{ controller_host_name }}:443' } #TODO : provide the option of HTTP(S) and port as params
    - { setting: 'http.event.accountName=', value: '{{ global_analytics_account_name }}' }
    - { setting: 'http.event.accessKey=', value: '{{ account_access_key }}' }
    - { setting: 'http.event.name=', value: '{{ account_name }}' }
  no_log: yes
