---
galaxy_info:
  author: Israel Ogbole
  description: installs jq to /usr/local/bin
  license:
    - Apache2
  min_ansible_version: 2.8
  platforms:
    - name: Alpine
      verisions:
        - all
    - name: Archlinux
      verisions:
        - all
    - name: Debian
      versions:
        - buster
        - stretch
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
  galaxy_tags:
    - jq
    - json

dependencies: []
