---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker

#lint: |
#  set -e
#  yamllint .
#  flake8
#  ansible-lin

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:xenial}
    privileged: true
    command: ${MOLECULE_COMMAND:-"sleep infinity"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}