---
- hosts: windows
  tasks:
    - include_role:
        name: machine-agent
      vars:
        # Define Agent Type and Version 
        agent_version: 20.6.0
        agent_type: machine
        application_environment: "production"
        # Your controller details 
        controller_account_access_key: "ffdsfs" # Please add this to your Vault 
        controller_global_analytics_account_name: 'customer1-guid' # Please add this to your Vault 
        controller_host_name: "saas.appdynamics.com" # Your AppDynamics controller 
        controller_account_name: "customer1" # Please add this to your Vault 
        sim_enabled: "false"
        ssl_enabled: "false"
        controller_port: "443"
        analytics_event_endpoint: "https://fra-ana-api.saas.appdynamics.com:443"
        enable_analytics_agent: true
    


