---
- name: Upgrade all apt packages
  apt: update_cache=yes force_apt_get=yes

- name: install tools and pre-requisites for Debian variants
  apt:
    state: present
    name:
    - unzip

# needed for AWS S3  boto3 and botocore 
- name: Install Python and pip for Debian variants
  apt:
    name:
      - python3
      - python3-pip
    state: present

