---
- debug:
    msg: "logger apply to {{ agents_to_set_loggers_for }} "

# --------------[ DB ]------------------
- include_tasks: db_logger_linux.yaml
  when: >
    (ansible_os_family == 'RedHat' or  ansible_os_family == 'Debian') and
    (agents_to_set_loggers_for | select('match', 'db' ) or
    ( agent_type is defined and agent_type == "db" ))

- include_tasks: db_logger_win.yaml
  when: >
    (ansible_os_family == 'Windows') and
    (agents_to_set_loggers_for | select('match', 'db' ) or
    ( agent_type is defined and agent_type == "db" ))

# -------------[ Java ]-----------------
- include_tasks: java_logger_linux.yaml
  when: >
    (ansible_os_family == 'RedHat' or  ansible_os_family == 'Debian') and
    (agents_to_set_loggers_for | select('match', '.*java.*' ) or
    ( agent_type is defined and agent_type is regex('.*java.*')))

- include_tasks: java_logger_win.yaml
  when: >
    (ansible_os_family == 'Windows') and
    (agents_to_set_loggers_for | select('match', '.*java.*' ) or
    ( agent_type is defined and agent_type is regex('.*java.*')))

# -----------[ Machine ]----------------
- include_tasks: machine_logger_linux.yaml
  when: >
    (ansible_os_family == 'RedHat' or  ansible_os_family == 'Debian') and
    ( agents_to_set_loggers_for | select('match', 'machine' ) or
    ( agent_type is defined and agent_type == "machine" ))

- include_tasks: machine_logger_win.yaml
  when: >
    (ansible_os_family == 'Windows') and
    ( agents_to_set_loggers_for | select('match', 'machine' ) or
    ( agent_type is defined and agent_type == "machine" ))
