
- name: Validate parameters
  include: validate_parameters.yml

###### Note #########
## Unlike Linux, Windows is unable to use the aws-s3 module because Ansible doesn't quite support running Python modules on Windows. 
# The workaround this limiation, we will download the agents from S3 to the Ansible controller then copy the files to the Windows host
- name: Check Ansibile controller OS requirements - RedHat
  include: rhel_server_requirements.yml
  when: "ansible_os_family == 'RedHat'"
  delegate_to: localhost
  
- name:  Check Ansibile controller OS requirements - Debian
  include: debian_server_requirements.yml
  when: "ansible_os_family == 'Debian'"
  delegate_to: localhost   

- name: Set Installation facts - specific to Nexus
  set_fact:
    machine_agent_search_parameters: "r={{ nexus.appd.repositoryId }}&g={{ nexus.appd.groupId }}&a={{ nexus.appd.machine_agent_artifactId }}&v={{ nexus.appd.machine_agent_version }}&p={{ nexus.appd.machine_agent_packaging }}"
    application_agent_search_parameters: "r={{ nexus.appd.repositoryId }}&g={{ nexus.appd.groupId }}&a={{ nexus.appd.application_agent_artifactId }}&v={{ nexus.appd.application_agent_version }}&p={{ nexus.appd.application_agent_packaging }}"
    netviz_agent_search_parameters: "r={{ nexus.appd.repositoryId }}&g={{ nexus.appd.groupId }}&a={{ nexus.appd.netviz_agent_artifactId }}&v={{ nexus.appd.netviz_agent_version }}&p={{ nexus.appd.netviz_agent_packaging }}"

- name: Set AppDynamics controller and account facts - Production Controller 
  when: application_environment|lower is match('prod.*')
  set_fact:
    account_access_key: "{{ controller_environment.production.access_key }}"
    account_name: "{{ controller_environment.production.account_name }}"
    global_analytics_account_name: "{{ controller_environment.production.global_account_name}}"
    controller_host_name: "{{ controller_environment.production.host_name }}"
  no_log: yes

- name: Set AppDynamics controller and account facts - NonProduction Controller 
  when: application_environment|lower is not match('prod.*')
  set_fact:
    account_access_key: "{{ controller_environment.nonproduction.access_key }}"
    account_name: "{{ controller_environment.nonproduction.account_name }}"
    global_analytics_account_name: "{{ controller_environment.nonproduction.global_account_name}}"
    controller_host_name: "{{ controller_environment.nonproduction.host_name }}"
  no_log: yes

- name: Set the unique host id so that machines appear correctly for APM
  win_environment:
    state: present
    level: machine
    name: "APPDYNAMICS_AGENT_UNIQUE_HOST_ID"
    value: "{{ host_name }}"

- name: Install Machine Agent
  include: machine-agent.yml

- name: Install Java Agent
  include: dotnet-agent.yml

- name: Clean up - remove {{ ma_agent_dest_file }} 
  win_file:
    path: "{{ machine_agent_dest_folder_win }}/{{ ma_agent_dest_file }}"
    state: absent

- name: Clean up - remove {{ dotnet_agent_dest_file }} 
  win_file:
    path: "{{ dot_agent_dest_folder_win }}\\{{ dotnet_agent_dest_file }}"
    state: absent
