---

- name: Validate application_environment
  assert:
    that: application_environment is defined
    msg: 'An application environment must be provided'

- name: Validate db_agent_name
  assert:
    that:  db_agent_name is defined
    msg: 'An DB agent name must be provided'


#- name: Validate aws_region
#  assert:
#    that: aws_region is defined
#   msg: 'A aws region must be provided'    
