---
- name: Converge
  hosts: all
  tasks:
  - name: Update apt cache (on Debian).
    apt:
      update_cache: true
      cache_valid_time: 3600
    when: ansible_os_family == 'Debian'
  #roles:
    #- role: appdynamics.agents.java
- import_playbook: ../../machine.yaml
  vars:
        # Define Agent Type and Version 
        agent_version: 20.8.0
        agent_type: sun-java
        # The applicationName
        application_name: "IoT_API"
        tier_name: "login_service2" # ONLY required if agent type is not machine and db agent
        # Your controller details 
        controller_account_access_key: "ffdsfs" # Please add this to your Vault 
        controller_host_name: "saas.appdynamics.com" # Your AppDynamics controller 
        controller_account_name: "customer1"  # Please add this to your Vault 
        ssl_enabled: false
        sim_enabled: true
        controller_port: "443"
        analytics_event_endpoint: "http://ansible-20100nosshcont-bum4wzwa.appd-cx.com:7001"
        enable_analytics_agent: true
        machine_hierarchy: "AppName|Owners|Environment|" # Make sure it ends with a |