- block:
    - name: Check tomcat configuration path is present
      stat: 
        path: "{{ app.tomcat_config | dirname }}"
      register: p
      failed_when: p.stat.isdir is not defined
  rescue: 
    - fail:
        msg: "Please make sure {{ app.tomcat_config | dirname }} is present. Is tomcat installed?"
      tags:
        - skip_ansible_lint

- name: Add appd instrumentation to tomcat
  become: yes
  register: instrumentation
  blockinfile:
    path: "{{ app.tomcat_config }}"
    #regex: ".+javaagent:.+"
    block: |
      export APPDYNAMICS_AGENT_APPLICATION_NAME="{{ app.application_name }}"
      export APPDYNAMICS_AGENT_TIER_NAME="{{ app.tier_name }}"
      export APPDYNAMICS_AGENT_NODE_NAME="{{ app.node_name }}"
      CATALINA_OPTS="$CATALINA_OPTS -javaagent:{{ java_agent_dest_folder_linux }}/javaagent.jar{{ ' -Dappdynamics.http.proxyHost='+proxy_host if enable_proxy else '' }}{{' -Dappdynamics.http.proxyPort='+proxy_port if enable_proxy else ''}}"
    create: yes
    owner: "{{ app.user }}"
    group: "{{ app.user }}"
    mode: 'u+x'
    state: present
    backup: "{{ app.backup }}"
