---
# App owners would either need to chown the entire agent folder to their app's user  OR grant their app's user read/write access to the agent folder 
- name: Java linux Block
  become: true
  block: 
    - name: Ensures application agent dir exists
      file: 
        path: "{{ java_agent_dest_folder_linux }}/"
        state: directory     
        mode: 0755
        #recurse: yes
      #changed_when: false # this ensures this task is idempotent 

    - name: Downloading Java Agent to target
      get_url:
        url: '{{ agent_download_url.stdout }}'
        dest: '{{ java_agent_dest_folder_linux }}/{{ java_agent_dest_file }}'
        force: 'true'
        remote_src: yes
      changed_when: false
    
    - name: Unzip the application agent file
      unarchive: 
        src: "{{ java_agent_dest_folder_linux }}/{{ java_agent_dest_file }}"
        dest: "{{ java_agent_dest_folder_linux }}"   
        creates: "{{ java_agent_dest_folder_linux }}/javaagent.jar"

    - name: Install java-agent config
      template:
        src: templates/application-agent-controller-info.xml.j2
        dest: '{{ java_agent_dest_folder_linux }}/conf/controller-info.xml'
        mode: 0755  

    #- name: Verify java agent config
    #  command: less  '{{ java_agent_dest_folder_linux }}/conf/controller-info.xml'
    #  register: content
    #  ignore_errors: yes

    #- name: Show config file content
    #  debug:
    #    var: content

    - name: Clean up - remove {{ java_agent_dest_file }} 
      file:
        path: "{{ java_agent_dest_folder_linux }}/{{ java_agent_dest_file }}"
        state: absent  
      changed_when: false # this ensures this task is idempotent 
