- include_tasks: java-agent-linux.yml
  when: >
    (ansible_os_family == 'RedHat' or ansible_os_family == 'Debian') and
    not just_installed_java_agent

- include_tasks: java-agent-windows.yml
  when: >
    ansible_os_family == 'Windows'
    and not just_installed_java_agent
