---

- name: add openjdk-r ppa
  apt_repository:
    repo: 'deb http://security.debian.org/debian-security stretch/updates main'
    state: present
    update_cache: true
  when: "ansible_os_family == 'Debian'"

- name: Install OpenJDK on Debian
  apt:
     update_cache: yes
     name: 
      - software-properties-common
      - openjdk-8-jdk
     state: present
  when: "ansible_os_family == 'Debian'"
  
- name: Install OpenJDK on Redhat
  yum: 
    update_cache: yes
    name: java-1.8.0-openjdk
    state: installed
  when: "ansible_os_family == 'RedHat'"
