

# Edit standalone.sh 
# Enable the AppDynamics Java Agent 
# export JAVA_OPTS="$JAVA_OPTS -javaagent:$INSTALL_DIR/ver*/javaagent.jar -Dappdynamics.http.proxyHost=$PROXY_HOST -Dappdynamics.http.proxyPort=$PROXY_PORT"
 
#  Above statement should be added before the below statements 
#  while true;do
# if [ "x$LAUNCH_JBOSS_IN_BACKGROUND" = "X" ]; then

- name:  Add appd instrumentation to jboss
  replace:
    path: "{{ jboss_config }}"
    regexp: '^(?:.*export APPD(?:.|\s)+?\s*)?\s*while\s+true;\s*do\s*(if\s*\[.+LAUNCH_JBOSS_IN_BACKGROUND.+)'
    replace: |-
      export APPDYNAMICS_AGENT_APPLICATION_NAME="{{ application_name }}"
      export APPDYNAMICS_AGENT_TIER_NAME="{{ tier_name }}"
      export APPDYNAMICS_AGENT_NODE_NAME="{{ node_name }}"
      export JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,com.singularity"
      export JAVA_OPTS="$JAVA_OPTS -javaagent:{{ java_agent_dest_folder_linux }}/javaagent.jar{{ ' -Dappdynamics.http.proxyHost='+proxy_host if proxy_enabled else '' }}{{' -Dappdynamics.http.proxyPort='+proxy_port if proxy_enabled else ''}}"
      while true;do
      \1
    backup: yes
  notify: Restart app listener
