
---
- name: Check jboss is present
  become: yes
  include: check_jboss.yml

- name: Import java role
  include_role:
    name: appdynamics.agents.java
  vars:
    application_details_in_config: no

- name: Add jboss user to {{ appdynamics_user }} group
  become: yes
  include: add_user.yml

- name: Instrument jboss
  become: yes
  include: jboss.yml
