- include_tasks: check_jboss.yml

- include_role:
    name: appdynamics.agents.java
    # use role variables in following tasks when public: yes
    public: yes
    #tasks_from: app_instrument_main
    # here what goes into appdynamics.agents.java:
    # - notify: Restart app listener
    # - app_user - can be added to appdynamics group

- include_tasks: instrument_jboss.yml
