- include_tasks: check_jboss.yml

# include this role to verify java agent after app restart
- include_role:
    name: verify_java_restart
  when: restart_app | bool

- include_tasks: instrument_jboss.yml
