---
- name: Install jq
  package:
    name: jq
    state: present
  delegate_to: localhost

- name: Install jq to ansible controller -  macOS
  community.general.homebrew_tap:
    state: present
    name: 
      - jq
  delegate_to: localhost
  when: "ansible_os_family == 'Darwin'"