- include_tasks: validate_parameters.yml

#- include_tasks: install_jq.yml

- debug: 
     msg:  "Agent variables: type=> {{ agent_type }} version=> {{ agent_version }}"

- include_tasks: get_agent.yml

- name: Set AppDynamics access key facts
  set_fact:
    account_access_key: "{{ controller_account_access_key }}"
  no_log: yes

- name: Set AppDynamics controller facts
  set_fact:
    account_name: "{{ controller_account_name }}"
    global_analytics_account_name: "{{ controller_global_analytics_account_name }}"
    controller_host_name: "{{ controller_host_name }}"
    analytics_event_endpoint: "{{ analytics_event_endpoint }}"
    sim_enabled: "{{ sim_enabled }}"
    ssl_enabled: "{{ ssl_enabled }}"
    controller_port: "{{ controller_port }}"
    enable_analytics_agent: "{{ enable_analytics_agent }}"
    machine_hierarchy: "{{ machine_hierarchy }}"

- name: Set HTTPS Protocol facts
  set_fact:
      controller_protocol: "{% if ssl_enabled|bool %}https{% else %}http{% endif %}"

- name: Print params 
  vars:
     params: "
      SSL enabled = {{ ssl_enabled }} |
      Controller={{ controller_protocol }}://{{ controller_host_name }}:{{ controller_port }} |
      controller_account_name={{ controller_account_name }} |
      analytics_event_endpoint={{ analytics_event_endpoint }} "
  debug: 
    msg: "{{ params.split('|') }}"