---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_user: appdynamics
      ansible_password: molecule123!
      ansible_port: 5985
      ansible_host: localhost
      # ansible_winrm_server_cert_validation: ignore
# lint: |
#   set -e
#   yamllint .
#   flake8
#   ansible-lint
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK:-prepare.yaml}
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible


# - address: ssh_endpoint
#   identity_file: ssh_identity_file  # mutually exclusive with password
#   instance: instance_name
#   port: ssh_port_as_string
#   user: ssh_user
#   password: ssh_password  # mutually exclusive with identity_file
#   become_method: valid_ansible_become_method  # optional
#   become_pass: password_if_required  # optional

# - address: winrm_endpoint
#   instance: instance_name
#   connection: 'winrm'
#   port: winrm_port_as_string
#   user: winrm_user
#   password: winrm_password
#   winrm_transport: ntlm/credssp/kerberos
#   winrm_cert_pem: <path to the credssp public certificate key>
#   winrm_cert_key_pem: <path to the credssp private certificate key>
#   winrm_server_cert_validation: validate/ignore