---
- hosts: all
  tasks:
    - include_vars: vars/controller.yaml
    - include_role:
        name: appdynamics.agents.db
      vars:
        agent_version: 20.9.0
        agent_type: db
        db_agent_name: "ProdDBAgent"
        install_jre: true # set to false if the target machine already contains a JRE
