---
- hosts: linux
  tasks:
    - name: Include variables for the controller settings
      include_vars: vars/controller.yaml

    - include_role:
        name: appdynamics.agents.dotnet_core
      vars:
        # Define Agent Type and Version
        agent_version: 20.9.0
        agent_type: dotnet-core

        # The applicationName
        application_name: "IoT_API" # ONLY required if agent type is not machine or db
        tier_name: "dotnet_core_tier" # ONLY required if agent type is not machine or db

        # Directory permissions for agent. These can be set at host level in the invertory as well
        agent_dir_permission:  #defaults to root:root if not specified
          user:  "appdynamics" # This user must pre-exist. It is recommended to use the PID owner of your Java app
          group: "appdynamics" # This group must pre-exist

        # # Your controller details
        # controller_account_access_key: "b0248ceb-c954-4a37-97b5-207e90418cb4" # Please add this to your Vault
        # controller_host_name: "ansible-20100nosshcont-bum4wzwa.appd-cx.com" # Your AppDynamics controller
        # controller_account_name: "customer1" # Please add this to your Vault
        # enable_ssl: "false"
        # controller_port: "8090"
