---
- hosts: all
  roles:
    - role: appdynamics.agents.java
      vars:
        agent_version: 20.10.0
        agent_type: sun-java
  pre_tasks:
    - name: Include variables for the controller settings
      include_vars: vars/controller.yaml
  tasks:
    - include_role:
        name: appdynamics.agents.instrument_tomcat
      vars:
        application_name: Tomcat
        tier_name: Tomcat
        tomcat_config: /etc/tomcat/conf.d/appdynamics.conf
        app_user: tomcat
        tomcat_service: tomcat
        restart_app: yes
