---
- hosts: all
  tasks:
    - include_vars: vars/controller.yaml
    - include_role:
        name: appdynamics.agents.java
      vars:
        # Define Agent Type and Version
        agent_version: 20.9.0
        agent_type: sun-java
        # The applicationName
        application_name: "IoT_API" # ONLY required if agent type is not machine or db
        tier_name: "java_tier" # ONLY required if agent type is not machine or db
