---
#- name: update apt cache
#  apt: update_cache=yes force_apt_get=yes

- name: install tools and pre-requisites for Debian variants
  apt:
    state: present
    name:
    - unzip

- name: Install jq to ansible controller -  Debian variants
  apt:
    state: present
    name:
    - jq
  delegate_to: localhost
