---
- name: install tools and pre-requisites for RedHat variants
  yum:
    update_cache: yes
    name:
     - unzip
    state: installed

# -----------------------------------------------------------------------------
# Make sure the lxml module is installed on the target server. It seems that
# this also requires check to see if pip is installed
- name: Get the python version
  community.general.python_requirements_info:
  register: pythonInfo
  
- debug:
    msg: "{{ pythonInfo.python_version }}"

# - name: Make sure epel-release is available
#   become: true
#   yum:
#     update_cache: yes
#     name: epel-release
#     enablerepo: "extras"
#     state: installed
#
# - name: List Repos
#   yum:
#     list: repos
#   register: r
#
# - debug:
#      msg: "{{ r }}"
#
# - name: List Packages
#   yum:
#     list: available
#   register: packkages
#
# - name: Display all python-pip packages
#   debug:
#     var: item
#   loop: "{{ packkages | json_query(pip_packages_query) }}"
#   vars:
#     pip_packages_query: "results[?(@name=~/python?-pip/)].name"
#
- name: Make sure pip3 is available
  yum:
    update_cache: yes
    name: python3-pip
    enablerepo: "extras,epel"
    state: installed
  when: pythonInfo.python_version is regex("3\..*")

- name: Make sure pip2 is available
  yum:
    update_cache: yes
    name: python2-pip
    enablerepo: "extras,epel"
    state: installed
  when: pythonInfo.python_version is regex("2\..*")

- name: install lxml for XML file manipulations
  pip:
    name: lxml
#-------------------------------------------------------------------------------
