name: "galaxy deploy"
on:
  push:
   branches: [ master, develop ]
jobs:
  deploy_galaxy:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        distro:
          - centos7
        #  - debian10
        collection_role:
          - db
          - java
          - machine
    steps:
      - name: Check out code
        uses: actions/checkout@v2
     
      - name: Set APPD_RELEASE_VERSION
        run: echo "APPD_RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Python 3s
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule-docker docker yamllint ansible-lint flake8 ansible
      
      - name: Deploy to Galaxy 
        run: >-
          ansible-playbook build/galaxy_deploy.yml
        env: 
           ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
           APPD_RELEASE_VERSION: ${{ env.APPD_RELEASE_VERSION }}
