name: "appdynamics.agents.java(win)"
on:
  push:
    paths:
      - 'roles/java/**'
      - 'molecule/java/**'
      - '.github/workflows/java_agent_ci.yml'
      - 'roles/common/**'
  pull_request:
    paths:
      - 'roles/java/**'
      - 'molecule/java/**'
      - '.github/workflows/java_agent_ci.yml'
      - 'roles/common/**'
jobs:
  molecule-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: true
      matrix:
        distro:
          # - windows2016
          - windows2019
        collection_role:
          - java
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
          
      - name: Set git to use LF
        shell: cmd
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      
      - name: Check out code
        uses: actions/checkout@v2

      # - name: Allow basic auth
      #   shell: powershell
      #   run: |
      #     Set-Item -Path WSMan:\localhost\Service\Auth\Basic -Value $true

      - name: Prepare WinRM
        shell: cmd
        run: | 
          winrm quickconfig -q -force
          winrm enumerate winrm/config/Listener
      - name: Create user
        shell: cmd
        env:
          WINRM_PASSWORD: ${{ secrets.WINRM_PASSWORD }}
        run: | 
          net user appdynamics "%WINRM_PASSWORD%" /add /passwordchg:no /passwordreq:yes /active:yes /Y
          net localgroup Administrators appdynamics /add
      
      # https://github.com/marketplace/actions/setup-wsl#action
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1
        with:
          wsl-shell-command: bash -e -u -o pipefail

      - name: Update path in WSL
        run: |
          echo 'PATH=$HOME/.local/bin:$PATH' >> ~/.vars
          source ~/.vars
          echo $PATH

      - name: Checkout pip cache
        uses: actions/cache@v2
        with:
          path: ./pip-cache
          key: ${{ runner.os }}-pip-ansible-${{ hashFiles('molecule/requirements-windows.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-ansible

      - name: Install Ansible and test dependencies in WSL
        run: |
          echo $PATH
          source ~/.vars
          mkdir -p ./pip-cache
          sudo apt-get update
          sudo apt-get install jq curl python3-pip git libffi-dev libssl-dev -y
          pip3 install --cache-dir=./pip-cache --user -r molecule/requirements-windows.txt
      
      - name: Build the collection
        run: |
          source ~/.vars
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          echo $collection_file
          echo "COLLECTION_FILE=$collection_file" >> ~/.vars
        
      - name: Install the collection
        run: |
          source ~/.vars
          ansible-galaxy collection install $COLLECTION_FILE
      
      - name: Run role tests
        run: >-
          source ~/.vars &&
          molecule --version &&
          ansible --version &&
          molecule --base-config molecule/base-windows.yml --debug test -s ${{ matrix.collection_role }}
        env: 
          PY_COLORS: '1'
          WINRM_PASSWORD: ${{ secrets.WINRM_PASSWORD }}
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          WSLENV: PY_COLORS:WINRM_PASSWORD:ANSIBLE_FORCE_COLOR:MOLECULE_DISTRO
