name: "appdynamics.agents.machine"
on:
  push:
    paths:
      - 'roles/machine/**'
      - 'molecule/machine/**'
      - 'molecule/base-docker.yml'
      - '.github/workflows/machine_agent_ci.yml'
      - 'roles/common/**'
  pull_request:
    paths:
      - 'roles/machine/**'
      - 'molecule/machine/**'
      - 'molecule/base-docker.yml'
      - '.github/workflows/machine_agent_ci.yml'
      - 'roles/common/**'
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        distro:
          - centos7
          - debian10
        collection_role:
          - machine
        ansible_ver:
          - "==2.9.*"
          - "==2.10.*"
          - ">=2.10" # latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install "ansible${{ matrix.ansible_ver }}" molecule-docker docker yamllint ansible-lint flake8 lxml
      
      - name: Build the collection
        run: |
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          echo "COLLECTION_FILE=$collection_file" >> $GITHUB_ENV
        
      - name: Install the collection
        run: ansible-galaxy collection install ${{ env.COLLECTION_FILE }}
      
      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          molecule --base-config molecule/base-docker.yml --debug test -s ${{ matrix.collection_role }} 
        env: 
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
